@startuml Factory
skinparam LineType Ortho

interface IProduct

class ProductA implements IProduct
class ProductB implements IProduct
class ProductC implements IProduct


class ProductFactory {
	+GetProduct(string productName) : IProduct
	+GetProduct(Type productType) : IProduct
	+GetProduct<T>() where T is IProduct : IProduct
}

class Consumer {

	+ProductFactory Factory
	Main() : void
}

Consumer --> ProductFactory
Consumer --> IProduct

ProductFactory --> IProduct

@enduml
